result = 1 + 2
print('result =', result)
origin_result = result
result = result - 1
print('result =', result)
origin_result = result
result = result * 2
origin_result = result
print('result =', result)
result = result ** 3
origin_result = result
print('result =', result)
result = result + 8
origin_result = result
print('result =', result)
result = result % 7
origin_result = result
print('result =', result)
result = result // 2
origin_result = result
print('result =', result)